version: "2"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: social2
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - .:/opt/app
    ports:
      - "3000:3000"
    depends_on:
      - db